# Generated by Django 3.2 on 2021-07-12 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20210712_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.DeleteModel(
            name='PostViews',
        ),
    ]
