# Generated by Django 3.2 on 2022-06-18 05:54

from django.db import migrations
import tagify.models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_alter_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=tagify.models.TagField(blank=True, default='Other', max_length=100, verbose_name='tags'),
        ),
    ]
