# Generated by Django 3.2 on 2022-06-18 04:21

from django.db import migrations
import tagify.models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_alter_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=tagify.models.TagField(verbose_name='languages'),
        ),
    ]
